spring:
  datasource:
    password: Pi-3141592653589
    url: jdbc:sqlserver://localhost:1433;databaseName=rgsTask;
    username: sa
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  sql:
    init:
      mode: always
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
